return {
	station3 = {
		acceleration = 0.207,
		autoheal = 15,
		brakerate = 0.6486,
		buildcostenergy = 3400,
		buildcostmetal = 175,
		buildpic = "ARMSPID.PNG",
		buildtime = 5090,
		canmove = true,
		category = "ALL BOT MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "28 15 28",
		collisionvolumetype = "box",
		description = "debug sphere",
		energymake = 0.7,
		energyuse = 0.7,
		explodeas = "smallexplosiongeneric",
		footprintx = 0,
		footprintz = 0,
		hidedamage	= true,
		hitdensity	= 0,
		idleautoheal = 5,
		idletime = 600,
		levelground	= false,
		stealth	= true,
		indestructible	= true,
		blocking	= false,
		maxdamage = 850,
		maxvelocity = 2.385,
		maxwaterdepth = 16,
		movementclass = "TBOT2",
		mygravity = 10000,
		name = "station2",
		nochasecategory = "ALL",
		objectname = "station1.s3o",
		--script = "dbg_sphere.cob",
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 550,
		stealth = true,
		strafetoattack = true,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.749,
		turnrate = 1290.29993,
		upright = true,
		customparams = {
			model_author = "Beherith",
			nohealthbars = true,
			normaltex = "unittextures/station_normal.dds",
			subfolder = "other",
		},
	},
}

